### ISSUE TITLE
Using lower levels functions in higher level functions

### ISSUE THREAD

**Issue by jbkunst** [edgararuiz-zz/dbplot#1]
Hi @edgararuiz 

Very nice package, very clever. I'm waiting the opportunity to use it.

Why not use your lower levels functions in your higher level functions, so the maintenance is a bit easier due you don't repeat code. So, as example:

```r
dbplot_histogram <- function(data, x, bins = 30, binwidth = NULL){

  db_compute_bins (data, x, bins = bins, binwidth = binwidth)  %>%
    ggplot() +
    geom_col(aes(x, n)) +
    labs(x = x,
         y = "count")
}
```

Thanks again for your package.

**Comment by edgararuiz-zz** [comment]
Hi @jbkunst , thank you, I appreciate it. And you're right, that's how I initially coded it, but had issues with using the `x` var as the name inside `ggplot2`.  My plan is to revisit this approach.
