### ISSUE TITLE
Support color aesthetic for boxplots

### ISSUE THREAD

**Issue by lorenzwalthert** [edgararuiz-zz/dbplot#27]
I'd like to produce an image like the one below, but if I am not mistaken, currently a `color` aesthetic is not supported in `dbplot_boxplot()` as well as `db_compute_boxplot()`. Would you consider adding this feature? Alternatively, if the argument `x`  in `db_compute_boxplot()` could take multiple grouping variables, that would already be an improvement. Thanks for maintaining this package.
![boxplots](https://user-images.githubusercontent.com/10477073/65757531-9f9ee980-e117-11e9-81f5-09116b6b91c0.png)

**Comment by edgararuiz-zz** [comment]
HI @lorenzwalthert , just added support for `vars()` as the `x` argument so that `db_compute_boxplot()` works with single and multiple grouping vars.  I'll have to look into how we could properly map aesthetics to the `dbplot_boxplot()` function. Hopefully, in the meanwhile, this works for you
