### ISSUE TITLE
db_compute_raster dropping empty bins

### ISSUE THREAD

**Issue by stPhena** [edgararuiz-zz/dbplot#5]
First of all thank you for this nice (and in my case, life-saving) package.

I have a dataset of records (sightings) with their latitude and longitude, and I am using the function `db_compute_raster(lon, lat, fill = n(), resolution = 500) ` to calculate density over a spatial grid. I am using this package because of its seamless integration with sparklyr.

The computation is done correctly but the output drops the bins - i.e. the lat-lon pairs - where the count was zero. This means that I will have empty areas when visualising with ggplot `geom_raster`. Is there the possibility of adding the choice of not dropping them?

**Comment by edgararuiz-zz** [comment]
Hi @Phenagen , thanks, I'm so glad you like the package!

Let me see what I can do for you on that, I think we could add an argument to turn that on and off for `db_compute_raster()`.  May I ask the reason why `dbplot_raster()` is not being used, is it because of this same problem, or is there something else I can do to make this helper function better?

**Comment by stPhena** [comment]
Thank you for the quick reply!
I assume the issue resides in `summarise(fill = !(!fillname))`, because `summarise()` does not allow, if I understood correctly, an argument similar to `.drop=FALSE`.

And I use `db_compute_raster()` because I need to perform other calculations on the results after this one.

**Comment by jbkunst** [comment]
Hi @Phenagen ,

In the meantime, remeber you can (pre)use `tidyr::complete` to get a data frame with all `lat`/`lon` combinations.  

In the next example note the number of rows.

``` r
library(dbplot)
library(tidyr)

df <- db_compute_raster(faithful, eruptions, waiting)
df
#> # A tibble: 246 x 3
#> # Groups:   x [?]
#>    eruptions waiting `n()`
#>        <dbl>   <dbl> <int>
#>  1     1.600   51.48     1
#>  2     1.635   63.67     1
#>  3     1.670   58.90     1
#>  4     1.705   53.60     1
#>  5     1.740   46.71     2
#>  6     1.740   47.77     1
#>  7     1.740   53.60     1
#>  8     1.740   57.84     1
#>  9     1.740   61.55     1
#> 10     1.775   45.65     1
#> # ... with 236 more rows

df %>% ungroup() %>% complete(eruptions, waiting, fill = list(`n()` = 0))
#> # A tibble: 3,876 x 3
#>    eruptions waiting `n()`
#>        <dbl>   <dbl> <dbl>
#>  1       1.6   43.00     0
#>  2       1.6   44.59     0
#>  3       1.6   45.65     0
#>  4       1.6   46.71     0
#>  5       1.6   47.77     0
#>  6       1.6   48.83     0
#>  7       1.6   49.89     0
#>  8       1.6   50.95     0
#>  9       1.6   51.48     1
#> 10       1.6   52.54     0
#> # ... with 3,866 more rows
```

Finally @edgararuiz, I noticed the result from ´db_compute_raster´ is a grouped data frame, not sure if this is needed. In the example the result needed to be ungrouped to use `complete`.

**Comment by edgararuiz-zz** [comment]
@jbkunst - Thanks for the great suggestion.  And you're right, about the grouped data frame, I'll look into un-grouping it prior to returning results.

@Phenagen - That's interesting, thank you for the clarification

**Comment by stPhena** [comment]
@jbkunst That was **exactly** was I was looking for. I had thought about `tidyr::complete()` but I did not know it could be used to complete numeric data. Thank you!
